# Generated by Django 5.0.14 on 2025-04-16 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('streaming', 'Streaming'), ('software', 'Software'), ('productivity', 'Productividad'), ('gaming', 'Videojuegos'), ('other', 'Otro')], default='other', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual'), ('weekly', 'Semanal'), ('once', 'Pago único')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('next_payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('card', 'Tarjeta'), ('paypal', 'PayPal')], default='card', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
