# Generated by Django 5.0.14 on 2025-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
    ]
