# Generated by Django 5.0.14 on 2025-04-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_paymentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='date',
            field=models.DateField(),
        ),
    ]
